### ISSUE TITLE
DSBCOO: First implementation

### ISSUE THREAD

**Issue by vincent-maillou** [vincent-maillou/qttools#27]

**Comment by vetschn** [comment]
This has some related issues, that will probably be closed together:
- [ ] #12 
- [ ] #28 
- [ ] #20 

Some tasks that need to be done and things that need to be addressed:

- [ ] DSBSparse matrices need to support higher dimensional stacking. For this we need to figure out how to distribute the dimensions accross ranks. Should we always split up only along the first and last dimension?
- [ ] Make the testing workflow MPI aware.
- [ ] Support more complicated indexing in the DSBlockIndexer.
- [ ] The current way of doing the dense, batched selected inversion has to change since I removed the stack_slice parameter of `.to_dense()`.
