### ISSUE TITLE
Extend DBCSR get_block() to return sparse block

### ISSUE THREAD

**Issue by vincent-maillou** [vincent-maillou/qttools#4]
- Add optional argument to get_block(): dense : bool = False
- False by default to avoid memory allocation in the default case
- Return the requested block in the CSR format

**Comment by vetschn** [comment]
Another thing to consider here, which @almaeder brought up the other day:

- [ ] Since we opted for block-wise contiguous storage we can cache the requested block data slice instead of always naively recomputing the mask. (From playing around a little bit, i estimate the total cache size should be on the order of kB and the speedup in case of cache hit should be _very noticeable_ :sweat_smile: )
